name: Python CI

on:
  push:
    branches: ["main", "develop"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

env:
  PYTHON_VERSION: '3.11'  # Updated to more recent version
  
permissions:
  contents: read
  security-events: write

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30  # Add timeout to prevent hanging workflows

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Updated from v3

      - name: Set up Python
        uses: actions/setup-python@v5  # Updated from v3
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'  # Add pip caching for better performance

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov

      - name: Run linting
        run: |
          pip install flake8
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        continue-on-error: true

      - name: Run tests with coverage
        run: |
          python -m pytest --cov=. --cov-report=xml --cov-report=term-missing || true
          
      - name: Upload coverage reports
        uses: codecov/codecov-action@v4
        if: always()
        with:
          file: ./coverage.xml
          fail_ci_if_error: false

  security-scan:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run security scan with Bandit
        uses: securecodewarrior/github-action-bandit@v1.0.1
        with:
          path: "."
          level: "low"
        continue-on-error: true

      - name: Run dependency vulnerability check
        run: |
          pip install safety
          safety check --json || true
        continue-on-error: true
